## Pandas practice problems

In [ ]:
# 1. Create a DataFrame of 5 students with columns: Name, age, Marks. Find the students with the highest marks
import pandas as pd
import numpy as np
df1 = pd.DataFrame({
    'Name': ['sid', 'aman', 'ansaf', 'jeetan', 'deba'],
    'Age': [24, 25, 23, 25, 24],
    'Marks': [88, 97, 90, 36, 97]
})
df1

     Name  Age  Marks
0     sid   24     88
1    aman   25     97
2   ansaf   23     90
3  jeetan   25     36
4    deba   24     97

In [ ]:
# find the students with the highest marks
highest_marks = df1['Marks'].max()
student_names = df1.loc[df1['Marks'] == highest_marks]
print("Complete details of students with the highest marks:\n", student_names)

# only student names (no other columns)
print("The students with the highest marks:\n", student_names['Name'])

Complete details of students with the highest marks:
    Name  Age  Marks
1  aman   25     97
4  deba   24     97
The students with the highest marks:
 1    aman
4    deba
Name: Name, dtype: object

In [ ]:
# 2. Load a csv file of your choice. Display its first 10 rows and summary statistics
import kagglehub
# Download latest version
path = kagglehub.dataset_download("goyaladi/iit-admissions-dataset")
print("Path to dataset files:", path)

Using Colab cache for faster access to the 'iit-admissions-dataset' dataset.
Path to dataset files: /kaggle/input/iit-admissions-dataset

In [ ]:
# load the csv file and display first 10 rows
df2 = pd.read_csv("/content/student_data.csv")
df2.head(10)

# df3 = pd.read_csc("/content/sample_data/california_housing_train.csv")

,Student ID,Student Name,Date of Birth,Field of Study,Year of Admission,Expected Year of Graduation,Current Semester,Specialization,Fees,Discount on Fees
0,165527,Bryan Rogers,2006-01-19,Computer Science,2020.0,2017.0,3.0,Web Development,155152.0,19572.0
1,635763,James Hogan,1999-05-23,Mechanical Engineering,2020.0,2020.0,2.0,Machine Learning,157870.0,14760.0
2,740021,David Robinson,1997-12-02,Civil Engineering,2017.0,2022.0,1.0,Network Security,55662.0,5871.0
3,433076,Susan Miller,1999-10-30,Computer Science,2021.0,2019.0,1.0,Data Science,134955.0,17284.0
4,441628,Brittany Martin,1998-01-10,Chemical Engineering,2016.0,2018.0,1.0,Network Security,125934.0,14871.0
5,837685,Melody Payne,1997-12-15,Mechanical Engineering,2016.0,2019.0,4.0,Web Development,131633.0,7565.0
6,268329,Erica Owens,2003-06-20,Mechanical Engineering,2020.0,2020.0,1.0,Artificial Intelligence,52994.0,5231.0
7,260971,Timothy Cruz,2003-05-19,Electrical Engineering,2021.0,2019.0,2.0,Artificial Intelligence,125632.0,18721.0
8,851589,Cassandra Johnson,1999-09-11,Chemical Engineering,2019.0,2020.0,1.0,Network Security,89571.0,16943.0
9,880448,Jonathan Ali,2006-03-31,Mechanical Engineering,2019.0,2020.0,4.0,Artificial Intelligence,61165.0,5748.0

In [ ]:
# summary statistics
df2.describe()
# df3.describe()

,Student ID,Year of Admission,Expected Year of Graduation,Current Semester,Fees,Discount on Fees
count,66070.000000,66069.000000,66069.000000,66069.000000,66069.000000,66069.000000
mean,549149.604843,2018.987271,2019.990313,2.500401,125032.084987,12447.053747
std,258563.802636,2.000402,1.995362,1.117765,43335.760233,8780.724498
min,100003.000000,2016.000000,2017.000000,1.000000,50000.000000,0.000000
25%,326507.750000,2017.000000,2018.000000,2.000000,87530.000000,5351.000000
50%,549066.000000,2019.000000,2020.000000,2.000000,125380.000000,10741.000000
75%,772661.750000,2021.000000,2022.000000,4.000000,162518.000000,18058.000000
max,999992.000000,2022.000000,2023.000000,4.000000,199999.000000,39736.000000

In [ ]:
# 3. Add a new column PASS/FAIL with marks>= 40, otherwise

df1['Result'] = np.where(df1['Marks'] >= 40, 'PASS', 'FAIL')

# using list comprehension
df1['Result2'] = ['PASS' if m >= 40 else 'FAIL' for m in df1['Marks']]

print(df1)

     Name  Age  Marks Result Result2
0     sid   24     88   PASS    PASS
1    aman   25     97   PASS    PASS
2   ansaf   23     90   PASS    PASS
3  jeetan   25     36   FAIL    FAIL
4    deba   24     97   PASS    PASS

In [ ]:
# 4. Group the data by a categorial column and compute the average of numeric columns: marks and age
df1_group = df1.groupby('Result')
df1_group.mean(['marks', 'age'])

         Age  Marks
Result
FAIL    25.0   36.0
PASS    24.0   93.0

In [ ]:
# 5. Merge two DataFrames: one containing Employee IDs and Names, another containing Employee IDs and Salaries
df_emp1 = pd.DataFrame({
    'Employee_ID': [1, 2, 3, 4, 5, 6],
    'Emp_Names': ['sid', 'aman', 'ansaf', 'jeetan', 'deba', 'sid']
})
df_emp2 = pd.DataFrame({
    'Employee_ID': [1, 2, 3, 4, 5, 6],
    'Salaries (in K)': [35, 15, 10, 40, 37, 30]
})
merge_df = pd.merge(df_emp1, df_emp2, on='Employee_ID')
print(merge_df)

   Employee_ID Emp_Names  Salaries (in K)
0            1       sid               35
1            2      aman               15
2            3     ansaf               10
3            4    jeetan               40
4            5      deba               37
5            6       sid               30

In [61]:
# 6. Sort the DataFrame by multiple columns: first by Department, then by Salary (descending)
merge_df['Department'] = ['IT', 'HR', 'Manager', 'HR', 'IT', 'IT']
merge_df = merge_df.sort_values(by=['Emp_Names', 'Salaries (in K)'], ascending=[True, False])
print(merge_df)

   Employee_ID Emp_Names  Salaries (in K) Department  Rank
1            2      aman               15         IT   2.0
2            3     ansaf               10         HR   2.0
4            5      deba               37    Manager   1.0
3            4    jeetan               40         HR   1.0
0            1       sid               35         IT   1.0
5            6       sid               30         IT   2.0

In [56]:
# 7. Replace all missing values in a DataFrame with column mean
# create a df7 with missing values
df7 = pd.DataFrame({
    'A': [1, np.nan, 4, np.nan, 5],
    'B': [60, 70, 81, 79, np.nan],
})
df7.fillna(np.round(df7.mean(),2), inplace=True)
print(df7)

# check for na (missing value) if yes then fill with mean using list comprehension
df7_2 = pd.DataFrame({
    'A': [1, np.nan, 4, np.nan, 5],
    'B': [60, 70, 81, 79, np.nan],
})

df7_2['A'] = [np.round(df7_2['A'].mean(),2) if np.isnan(x) else x for x in df7_2['A']]
df7_2['B'] = [np.round(df7_2['B'].mean(),2) if np.isnan(x) else x for x in df7_2['B']]
print(df7_2)

      A     B
0  1.00  60.0
1  3.33  70.0
2  4.00  81.0
3  3.33  79.0
4  5.00  72.5
      A     B
0  1.00  60.0
1  3.33  70.0
2  4.00  81.0
3  3.33  79.0
4  5.00  72.5

In [66]:
# 8. Create a new coloumn that shows the rank of employee by salary within their department
merge_df['Rank'] = merge_df.groupby('Department')['Salaries (in K)'].rank('dense', ascending=False)
print(merge_df)

merge_df = merge_df.sort_values(by=['Department', 'Rank'])
print('\n', merge_df)

   Employee_ID Emp_Names  Salaries (in K) Department  Rank
1            2      aman               15         IT   3.0
2            3     ansaf               10         HR   2.0
4            5      deba               37    Manager   1.0
3            4    jeetan               40         HR   1.0
0            1       sid               35         IT   1.0
5            6       sid               30         IT   2.0

    Employee_ID Emp_Names  Salaries (in K) Department  Rank
3            4    jeetan               40         HR   1.0
2            3     ansaf               10         HR   2.0
0            1       sid               35         IT   1.0
5            6       sid               30         IT   2.0
1            2      aman               15         IT   3.0
4            5      deba               37    Manager   1.0

In [67]:
# 9. Use apply() to increase every salary by 15%
merge_df['Salaries (in K)'] = merge_df['Salaries (in K)'].apply(lambda x: x * 1.15)
print(merge_df)

   Employee_ID Emp_Names  Salaries (in K) Department  Rank
3            4    jeetan            46.00         HR   1.0
2            3     ansaf            11.50         HR   2.0
0            1       sid            40.25         IT   1.0
5            6       sid            34.50         IT   2.0
1            2      aman            17.25         IT   3.0
4            5      deba            42.55    Manager   1.0

In [72]:
# 10. Convert a date column into day, month, and year components
# add date column in merge_df
merge_df['Date'] = pd.to_datetime(['2023-01-01', '2020-02-03', '2023-05-11', '2023-07-26', '2024-05-21', '2021-11-11'])

# adding day, month, year seperate column from Date column
merge_df['Day'] = merge_df['Date'].dt.day
merge_df['Month'] = merge_df['Date'].dt.month
merge_df['Year'] = merge_df['Date'].dt.year
print(merge_df)

   Employee_ID Emp_Names  Salaries (in K) Department  Rank       Date  Day  \
3            4    jeetan            46.00         HR   1.0 2023-01-01    1
2            3     ansaf            11.50         HR   2.0 2020-02-03    3
0            1       sid            40.25         IT   1.0 2023-05-11   11
5            6       sid            34.50         IT   2.0 2023-07-26   26
1            2      aman            17.25         IT   3.0 2024-05-21   21
4            5      deba            42.55    Manager   1.0 2021-11-11   11

   Month  Year
3      1  2023
2      2  2020
0      5  2023
5      7  2023
1      5  2024
4     11  2021